sudo: false

language: python

# Limit git depth to speed up build
git:
  depth: 5

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
      sudo: true
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      node_js: 8
      env: TOXENV=documents

addons:
  apt:
    packages:
      - aspell
      - aspell-en

install:
  - pip install tox
  - pip install codecov

script:
  - tox

# after_success:
#   - codecov

deploy:
  - provider: pypi
    user: facelessuser
    server: https://upload.pypi.org/legacy/
    password:
      secure: ""
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
    on:
      tags: true
      repo: facelessuser/pep562
      condition: "$TOXENV = documents"
  - provider: pages
    github_token: $GITHUB_TOKEN
    name: $GITHUB_USER
    email: $GITHUB_EMAIL
    skip_cleanup: true
    local_dir: site
    on:
      tags: true
      repo: facelessuser/pep562
      condition: "$TOXENV = documents"
